[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
bytecode_hash = "none"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
